=== dgutper960/EXAMEN_LMGS_UD4/Ejercicio1/Los_Remedios_SA_DTD.dtd
<!ELEMENT Los_Remedios_SA (pedido)>
<!ELEMENT pedido (nombre_trabajador,fecha_pedido,obsevaciones?,sucursal)>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT obsevaciones (#PCDATA)>
<!ELEMENT sucursal (departamento_exposicion,departamento_gestion)>
<!ATTLIST sucursal cogigo NMTOKEN #REQUIRED>
<!ELEMENT departamento_exposicion (direccion?,articulos)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT articulos (articulo)>
<!ELEMENT articulo (num_unidades_pedidas,precio_unidad,observaciones_articulo,plazo_revision)>
<!ATTLIST articulo codigo_articulo NMTOKEN #REQUIRED>
<!ELEMENT num_unidades_pedidas (#PCDATA)>
<!ELEMENT precio_unidad (#PCDATA)>
<!ELEMENT observaciones_articulo (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>
<!ELEMENT departamento_gestion (direccion?,albaran,pago)>
<!ELEMENT albaran (#PCDATA)>
<!ELEMENT pago (#PCDATA)>

=== dgutper960/EXAMEN_LMGS_UD4/Ejercicio1/Los_Remedios_SA_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Los_Remedios_SA SYSTEM "Los_Remedios_SA_DTD.dtd">
<Los_Remedios_SA>
    <pedido>
        <nombre_trabajador>Antonio Flores</nombre_trabajador>
        <fecha_pedido>12-02-1997</fecha_pedido>
        <obsevaciones>urgente</obsevaciones> <!-- opcional valores (urgente|incompleto)-->
        <sucursal cogigo="A6596325"> <!-- 8 CARACTERES PRIMERO UNA LETRA-->
          <departamento_exposicion>
            <direccion>Calle Los morales SN</direccion> <!-- opcional-->
            <articulos>
                <articulo codigo_articulo="AFT-659"> <!-- 3 mayusc - 3 num -->
                    <num_unidades_pedidas>24</num_unidades_pedidas>
                    <precio_unidad>4356</precio_unidad>
                    <observaciones_articulo>Nuevo y reacondicionado</observaciones_articulo>
                    <plazo_revision>15</plazo_revision>  <!-- expresado en dÃ­as -->
                </articulo>
            </articulos>
          </departamento_exposicion>
          <departamento_gestion>
            <direccion>Calle San Francisco - num 8</direccion>
            <albaran>12632</albaran>
            <pago>transferencia bancaria</pago>
        </departamento_gestion>
      </sucursal>
    </pedido>
</Los_Remedios_SA>
